### PR TITLE
2 shreyabadve35 find the cgpa and sgpa

### LINKED ISSUE #2: shreyabadve35 Find the CGPA and SGPA

### PR DESCRIPTION
**Pull request by Apollo-bot35**
DONE 
img

### CODE REVIEW

**Comment by Apollo-bot35** [comment]
DONE

**Comment by ombharamadev** [comment]
you need to add title in csv file which are file_name,sgpa,cgpa
image

**Comment by Apollo-bot35** [comment]
Ok sir

**Comment by Apollo-bot35** [comment]
Done sir
https://github.com/ombharamadev/data-project-1/tree/2-shreyabadve35-find-the-cgpa-and-sgpa

**Pull request closed without merging**
